/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}",],
  theme: {
    extend: {
      keyframes: {
        flashGreen: {
          '50%': { color: 'green' },
        },
        flashGreenTwo: {
          '50%': { color: 'green' },
        },
        flashRed: {
          '50%': { color: 'red' },
        }, 
        flashRedTwo: {
          '50%': { color: 'red' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)'},
          '10%': { transform: 'translateX(-20px)'},
          '20%': { transform: 'translateX(20px)'},
          '30%': { transform: 'translateX(-20px)'},
          '40%': { transform: 'translateX(20px)'},
          '50%': { transform: 'translateX(-20px)'},
          '60%': { transform: 'translateX(20px)'},
          '70%': { transform: 'translateX(-20px)'},
          '80%': { transform: 'translateX(20px)'},
        },
        shakeTwo: {
          '0%, 100%': { transform: 'translateX(0)'},
          '10%': { transform: 'translateX(-20px)'},
          '20%': { transform: 'translateX(20px)'},
          '30%': { transform: 'translateX(-20px)'},
          '40%': { transform: 'translateX(20px)'},
          '50%': { transform: 'translateX(-20px)'},
          '60%': { transform: 'translateX(20px)'},
          '70%': { transform: 'translateX(-20px)'},
          '80%': { transform: 'translateX(20px)'},
        },
        textGrow: {
          '0%': {transform: 'scale(0.1)'},
          '0%': {color: 'red'},
          '2%': {transform: 'scale(0.15)'},
          '4%': {transform: 'scale(0.2)'},
          '6%': {transform: 'scale(0.25)'},
          '8%': {transform: 'scale(0.3)'},
          '10%': {transform: 'scale(0.35)'},
          '12%': {transform: 'scale(0.4)'},
          '14%': {transform: 'scale(0.45)'},
          '16%': {transform: 'scale(0.5)'},
          '18%': {transform: 'scale(0.55)'},
          '20%': {transform: 'scale(0.6)'},
          '22%': {transform: 'scale(0.65)'},
          '24%': {transform: 'scale(0.7)'},
          '26%': {transform: 'scale(0.75)'},
          '28%': {transform: 'scale(0.8)'},
          '30%': {transform: 'scale(0.85)'},
          '32%': {transform: 'scale(0.9)'},
          '34%': {transform: 'scale(0.95)'},
          '36%': {transform: 'scale(1)'},
          '100%': {transform: 'scale(1)'},
        },
        textGrow2: {
          '0%': {transform: 'scale(0.1)'},
          '0%': {color: 'black'},
          '38%': {transform: 'scale(0.1)'},
          '38%': {color: 'black'},
          '40%': {transform: 'scale(0.15)'},
          '40%': {color: 'red'},
          '42%': {transform: 'scale(0.2)'},
          '44%': {transform: 'scale(0.25)'},
          '46%': {transform: 'scale(0.3)'},
          '48%': {transform: 'scale(0.35)'},
          '50%': {transform: 'scale(0.4)'},
          '52%': {transform: 'scale(0.45)'},
          '54%': {transform: 'scale(0.5)'},
          '56%': {transform: 'scale(0.55)'},
          '58%': {transform: 'scale(0.6)'},
          '60%': {transform: 'scale(0.65)'},
          '62%': {transform: 'scale(0.7)'},
          '64%': {transform: 'scale(0.75)'},
          '66%': {transform: 'scale(0.8)'},
          '68%': {transform: 'scale(0.85)'},
          '70%': {transform: 'scale(0.9)'},
          '72%': {transform: 'scale(0.95)'},
          '74%': {transform: 'scale(1)'},
          '100%': {transform: 'scale(1)'},
        },
        textFall: {
          

          '4%': {transform: 'translateY(10px)'},
          '6%': {transform: 'translateY(15px)'},
          '8%': {transform: 'translateY(20px)'},
          '10%': {transform: 'translateY(25px)'},
          '12%': {transform: 'translateY(30px)'},
          '14%': {transform: 'translateY(35px)'},
          '16%': {transform: 'translateY(40px)'},
          '18%': {transform: 'translateY(45px)'},
          '20%': {transform: 'translateY(50px)'},
          '22%': {transform: 'translateY(55px)'},
          '24%': {transform: 'translateY(60px)'},
          '26%': {transform: 'translateY(65px)'},
          '28%': {transform: 'translateY(70px)'},
          '30%': {transform: 'translateY(75px)'},
          // '100%': {transform: 'translateY(75px)'},
        },
        colorWave: {
          '0.1%': {transform: 'rotateY(0deg)'},
          '0.2%': {transform: 'rotateY(180deg)'},
          '0.3%': {transform: 'rotateY(0deg)'},
          '0.4%': {transform: 'rotateY(180deg)'},
          '0.5%': {transform: 'rotateY(0deg)'},
          '0.6%': {transform: 'rotateY(180deg)'},
          '0.7%': {transform: 'rotateY(0deg)'},
          '0.8%': {transform: 'rotateY(180deg)'},
          '0.9%': {transform: 'rotateY(0deg)'},
          '1%': {transform: 'rotateY(180deg)'},
          '1.1%': {transform: 'rotateY(0deg)'},
          '1.2%': {transform: 'rotateY(180deg)'},
          '1.3%': {transform: 'rotateY(0deg)'},
          '1.4%': {transform: 'rotateY(180deg)'},
          '1.5%': {transform: 'rotateY(0deg)'},
          '1.6%': {transform: 'rotateY(180deg)'},
          '1.7%': {transform: 'rotateY(0deg)'},
          '1.8%': {transform: 'rotateY(180deg)'},
          '1.9%': {transform: 'rotateY(0deg)'},
          '2%': {transform: 'rotateY(180deg)'},
          '2.1%': {transform: 'rotateY(0deg)'},
          '0%, 10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%, 100%': {color: 'yellow'},
          '2.5%, 12.5%, 22.5%, 32.5%, 42.5%, 52.5%, 62.5%, 72.5%, 82.5%, 92.5%': {color: 'red'},
          '5%, 15%, 25%, 35%, 45%, 55%, 65%, 75%, 85%, 95%': {color: 'blue'},
          '7.5%, 17.5%, 27.5%, 37.5%, 47.5%, 57.5%, 67.5%, 77.5%, 87.5%, 97.5%': {color: 'green'},
        }
      },
      animation: {
        flashGreen: 'flashGreen 1s 1',
        flashGreenTwo: 'flashGreenTwo 1s 1',
        flashRed: 'flashRed 1s 1',
        flashRedTwo: 'flashRedTwo 1s 1',
        shake: 'shake 1s 1',
        shakeTwo: 'shakeTwo 1s 1',
        textGrow: 'textGrow 5s 1',
        textFall: 'textFall 5s infinite',
        colorWave: 'colorWave 60s infinite',
        textGrow2: 'textGrow2 5s 1',
      },
      
    },
  },
  plugins: [],
}

